### ISSUE TITLE
Docker image tag for TRIQS release 3.0.1

### ISSUE THREAD

**Issue by krivenko** [TRIQS/docker#1]
Dear Nils,

I am not sure here is the right place to post this request, but could you please push a new tag for the 3.0.1 release to Docker Hub.
Thanks in advance!

Igor

**Comment by krivenko** [comment]
@Wentzell Could you please have a look at this? I would greatly appreciate having a TRIQS Docker image with TRIQS/triqs#819 fixed.

**Comment by Wentzell** [comment]
Dear @krivenko,

I have now added a docker image with the latest 3.0.1 release.
